name: CI

on:
  push:
    branches:
      - gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        env:
          REACT_APP_ACESS_TOKEN: ${{ secrets.REACT_APP_ACESS_TOKEN }}
        run: |
          echo We can use a variable multiple time: $REACT_APP_ACESS_TOKEN
          echo inside a multi-line script: $REACT_APP_ACESS_TOKEN

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
